/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteRouteImport } from './routes/layout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LayoutProductsIndexRouteImport } from './routes/layout/products/index'
import { Route as LayoutDashboardIndexRouteImport } from './routes/layout/dashboard/index'
import { Route as LayoutProductsNewRouteImport } from './routes/layout/products/new'
import { Route as LayoutProductsIdIndexRouteImport } from './routes/layout/products/$id/index'
import { Route as LayoutProductsIdEditRouteImport } from './routes/layout/products/$id/edit'

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/layout',
  path: '/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutProductsIndexRoute = LayoutProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutDashboardIndexRoute = LayoutDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutProductsNewRoute = LayoutProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutProductsIdIndexRoute = LayoutProductsIdIndexRouteImport.update({
  id: '/products/$id/',
  path: '/products/$id/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutProductsIdEditRoute = LayoutProductsIdEditRouteImport.update({
  id: '/products/$id/edit',
  path: '/products/$id/edit',
  getParentRoute: () => LayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/layout': typeof LayoutRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/layout/products/new': typeof LayoutProductsNewRoute
  '/layout/dashboard/': typeof LayoutDashboardIndexRoute
  '/layout/products/': typeof LayoutProductsIndexRoute
  '/layout/products/$id/edit': typeof LayoutProductsIdEditRoute
  '/layout/products/$id/': typeof LayoutProductsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/layout': typeof LayoutRouteRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/layout/products/new': typeof LayoutProductsNewRoute
  '/layout/dashboard': typeof LayoutDashboardIndexRoute
  '/layout/products': typeof LayoutProductsIndexRoute
  '/layout/products/$id/edit': typeof LayoutProductsIdEditRoute
  '/layout/products/$id': typeof LayoutProductsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/layout': typeof LayoutRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/layout/products/new': typeof LayoutProductsNewRoute
  '/layout/dashboard/': typeof LayoutDashboardIndexRoute
  '/layout/products/': typeof LayoutProductsIndexRoute
  '/layout/products/$id/edit': typeof LayoutProductsIdEditRoute
  '/layout/products/$id/': typeof LayoutProductsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/layout'
    | '/login/'
    | '/layout/products/new'
    | '/layout/dashboard/'
    | '/layout/products/'
    | '/layout/products/$id/edit'
    | '/layout/products/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/layout'
    | '/login'
    | '/layout/products/new'
    | '/layout/dashboard'
    | '/layout/products'
    | '/layout/products/$id/edit'
    | '/layout/products/$id'
  id:
    | '__root__'
    | '/'
    | '/layout'
    | '/login/'
    | '/layout/products/new'
    | '/layout/dashboard/'
    | '/layout/products/'
    | '/layout/products/$id/edit'
    | '/layout/products/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/layout': {
      id: '/layout'
      path: '/layout'
      fullPath: '/layout'
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layout/products/': {
      id: '/layout/products/'
      path: '/products'
      fullPath: '/layout/products/'
      preLoaderRoute: typeof LayoutProductsIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/layout/dashboard/': {
      id: '/layout/dashboard/'
      path: '/dashboard'
      fullPath: '/layout/dashboard/'
      preLoaderRoute: typeof LayoutDashboardIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/layout/products/new': {
      id: '/layout/products/new'
      path: '/products/new'
      fullPath: '/layout/products/new'
      preLoaderRoute: typeof LayoutProductsNewRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/layout/products/$id/': {
      id: '/layout/products/$id/'
      path: '/products/$id'
      fullPath: '/layout/products/$id/'
      preLoaderRoute: typeof LayoutProductsIdIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/layout/products/$id/edit': {
      id: '/layout/products/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/layout/products/$id/edit'
      preLoaderRoute: typeof LayoutProductsIdEditRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutProductsNewRoute: typeof LayoutProductsNewRoute
  LayoutDashboardIndexRoute: typeof LayoutDashboardIndexRoute
  LayoutProductsIndexRoute: typeof LayoutProductsIndexRoute
  LayoutProductsIdEditRoute: typeof LayoutProductsIdEditRoute
  LayoutProductsIdIndexRoute: typeof LayoutProductsIdIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutProductsNewRoute: LayoutProductsNewRoute,
  LayoutDashboardIndexRoute: LayoutDashboardIndexRoute,
  LayoutProductsIndexRoute: LayoutProductsIndexRoute,
  LayoutProductsIdEditRoute: LayoutProductsIdEditRoute,
  LayoutProductsIdIndexRoute: LayoutProductsIdIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
